import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Link from 'next/link'

const Home: NextPage = () => {

    return (
        <div>
            <Head>
                <title>Курсовой проект - NextJs | Java</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <section>
                <div className={`container-xl`}>
                    <div className={`row align-items-center`} style={{minHeight : '100vh'}}>
                        <div className={`col-6`}>
                            <div className={`card__title`}>
                                <h2>
                                    Курсовой проект
                                </h2>
                            </div>
                            <div className={`card__description mt-5`}>
                                Разработка информационной системы пункта проката<br/> велосипедов
                            </div>
                            <div className={`card__description mt-3`}>
                                Авторы проекта:<br/> Сотников Роман (ИВТ-401) и Максимов Сергей (ИСТ-401)
                            </div>
                            <div className={`mt-5`}>
                                <Link href={`/admin/clients`}>
                                    <a className={`btn btn-primary btn-lg`}>
                                        Начать работу
                                    </a>
                                </Link>
                            </div>
                        </div>
                        <div className={`col-6`}>
                            <div className={`card card-front-end card-min-h`}>
                                <div className={`card__label`}>
                                    Front-end
                                </div>
                                <div className={`card__title mt-4`}>
                                    <h2>
                                        Основа<br/> Next.JS<br/>
                                        Современно и надежно
                                    </h2>
                                </div>

                            </div>
                            <div className={`card card-back-end card-min-h mt-5`}>
                                <div className={`card__label`}>
                                    Back-end
                                </div>
                                <div className={`card__title mt-4`}>
                                    <h2>
                                        Основа<br/> Java<br/>
                                        Строго и <br/>практично
                                    </h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

        </div>
    )
}

export default Home
